version: build.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
before_build:
- ps: >-
    nuget restore


    [xml]$proj = Get-Content src/JsonApiSerializer/JsonApiSerializer.csproj

    $semver = $proj.Project.PropertyGroup.Version

    Set-AppveyorBuildVariable "semver" $semver

    Update-AppveyorBuild -Version "$semver-build.${env:APPVEYOR_BUILD_NUMBER}"
build:
  verbosity: minimal
artifacts:
- path: src\JsonApiSerializer\bin\Release\JsonApiSerializer.*.*.*.nupkg
  name: nupkg
deploy:
- provider: NuGet
  api_key:
    secure: Y8e8Ii8MaexIajVAG9/HN7l9OayIS14NlQz5322YA3TsI5QUfGjZTMt3Vfrxj9mL
  on:
    branch: master
- provider: GitHub
  release: v$(semver)
  auth_token:
    secure: vEWcO6lAHm6IXoP9zjEmCTkYSIcxnQVTYJmCoLXjvOcxDYOSglLSklu00I3JouUK
  artifact: nupkg
  on:
    branch: master